name = "python-command"
description = "Python Command"

[command]
shell = """
- we don't have to put everything in a single perform. You can use helper functions. Can you modularize the code a bit and use helper functions so it's easier to read?
"""
